# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.6"
    - name: Install requests
      run: pip install requests
    - name: Run
      run: python ucasclass.py
